//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avalon.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        public int id { get; set; }
        public string codigoServicio { get; set; }
        public string nombreServicio { get; set; }
        public string descripcionServicio { get; set; }
        public Nullable<int> idCentroCostos { get; set; }
        public Nullable<int> idSubCentroCostos { get; set; }
        public Nullable<int> idSubSubCentroCostos { get; set; }
        public Nullable<bool> esParaCompra { get; set; }
        public Nullable<bool> esParaVenta { get; set; }
    }
}
