//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avalon.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class socioNegocio
    {
        public int id { get; set; }
        public string tipoSocio { get; set; }
        public string codigoSocio { get; set; }
        public string grupoSocio { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public string nroDocumento { get; set; }
        public string razonSocial { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string email { get; set; }
        public string direccionFiscal { get; set; }
        public string direccionAlternativa { get; set; }
        public Nullable<int> idCondicionPago { get; set; }
        public string cuentaDetraccion { get; set; }
        public string cuentaCorriente1 { get; set; }
        public string cuentaMoneda1 { get; set; }
        public Nullable<int> cuentaCodigoBanco1 { get; set; }
        public string cuentaCorriente2 { get; set; }
        public string cuentaMoneda2 { get; set; }
        public Nullable<int> cuentaCodigoBanco2 { get; set; }
        public Nullable<bool> estado { get; set; }
        public string contacto1 { get; set; }
        public string telefonoContacto1 { get; set; }
        public string emailContacto1 { get; set; }
        public string contacto2 { get; set; }
        public string telefonoContacto2 { get; set; }
        public string emailContacto2 { get; set; }
        public string contacto3 { get; set; }
        public string telefonoContacto3 { get; set; }
        public string emailContacto3 { get; set; }
    
        public virtual condicionPago condicionPago { get; set; }
        public virtual tipoDocumentoIdentidad tipoDocumentoIdentidad { get; set; }
    }
}
